version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - shop-network

  webapi:
    build:
      context: ./ShopAPI
      dockerfile: Dockerfile
    container_name: shopapi
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=ShopDb;User=sa;Password=YourStrong!Passw0rd;"
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    networks:
      - shop-network

volumes:
  sqlserverdata:

networks:
  shop-network:
    driver: bridge