version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - shop-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -Q 'SELECT 1'"]
      interval: 30s  # wait longer between health checks
      timeout: 10s   # increase timeout to give SQL Server more time
      retries: 10    # increase number of retries

  webapi:
    build:
      context: ./ShopAPI
      dockerfile: Dockerfile
    container_name: shopapi
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=ShopDb;User=sa;Password=YourStrong!Passw0rd;Encrypt=True;TrustServerCertificate=True;"
    ports:
      - "5000:80"
    # depends_on:
    #   sqlserver:
    #     condition: service_healthy
    networks:
      - shop-network

volumes:
  sqlserverdata:

networks:
  shop-network:
    driver: bridge